name: Create Custom Labels

on:
  workflow_dispatch: # Trigger manually from GitHub UI

jobs:
  create-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Delete all existing labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            for (const label of labels.data) {
              try {
                await github.rest.issues.deleteLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name
                });
                console.log(`🗑️ Deleted label: ${label.name}`);
              } catch (error) {
                console.log(`⚠️ Could not delete label: ${label.name} – ${error.message}`);
              }
            }

      - name: Create custom labels
        uses: actions/github-script@v7
        with:
          script: |
            const customLabels = [
              { name: 'Custom Emulator', color: 'f9d0c4', description: 'Use custom Emulator' },
              { name: 'Skip-UI-Test', color: 'fef2c0', description: 'Don\'t run UI test' },
              { name: 'Stop', color: 'e99695', description: 'Don\'t trigger workflow' },
              { name: 'Ubuntu-latest', color: 'c5def5', description: 'To run on GitHub runner' }
            ];
            
            for (const label of customLabels) {
              try {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description
                });
                console.log(`✅ Created label: ${label.name}`);
              } catch (error) {
                console.log(`❌ Error creating label '${label.name}': ${error.message}`);
              }
            }
